### PR TITLE
chore: adds unique constraint to the approval queue

### LINKED ISSUE #78: Implement ability to re-submit rejected work; address multiple submission issue
Currently, if a work is rejected, there is no mechanism by which a user can submit it again for mod approval.

EDIT: Just heard from another user that this happened to them too, on or around August 24th -- a work was duplicated on submission to the approval queue; when the works approver ran across it, they rejected one and approved the other, but that resulted in the work being rejected -- so really in addition to Issue 639 Sigma filed to allow users to resubmit rejected works after corrections, we also need the submission process to check for/prevent having the same work be submitted multiple times simultaneously?

### PR DESCRIPTION
**Pull request by Figments**
adds a `UNIQUE` constraint to the approval queue table on `work_id`, guaranteeing that works can only ever be submitted to the queue once.

closes #78

### CODE REVIEW

**Comment by SigmasonicX** [comment]
What happens on the user's end when they try to add a work that was already added? I'd like for there to be a clear alert for them.

**Comment by Figments** [comment]
> What happens on the user's end when they try to add a work that was already added? I'd like for there to be a clear alert for them.

so return a user-readable error when the `UNIQUE` constraint is violated?

**Comment by SigmasonicX** [comment]
> > What happens on the user's end when they try to add a work that was already added? I'd like for there to be a clear alert for them.
> 
> so return a user-readable error when the `UNIQUE` constraint is violated?

Sure, like "This work has already been submitted for review".

**Comment by Figments** [comment]
```swift
func submitItem(_ id: String) async throws -> Response {
        let profile = try request.authService.getUser(withProfile: true).profile!
        return try await request.db.transaction { database in
            if let queueItem = try await ApprovalQueue.query(on: database).filter(\.$work.$id == id).first() {
                if queueItem.attempts > 3 {
                    throw Abort(.forbidden, reason: "You've already reached the maximum number of attempts for this work.")
                }
                queueItem.attempts += 1
                queueItem.status = .waiting
                try await queueItem.save(on: database)
                return Response(status: .ok)
            } else {
                guard let work = try await profile.$works.query(on: database).filter(\.$id == id).first() else {
                    throw Abort(.notFound, reason: "The work you're trying to add to the queue doesn't exist.")
                }
                if work.words < MIN_WORD_COUNT {
                    throw Abort(.badRequest, reason: "Your work must meet a minimum word count of \(MIN_WORD_COUNT) words before submission.")
                }
                let newItem = ApprovalQueue(workId: id)
                try await newItem.save(on: database)
                work.approvalStatus = .pending
                try await work.save(on: database)
                return Response(status: .ok)
            }
        }
    }
```

the function for submissions already checks for existing entries in order to increment an attempts counter. would this count for what you want, or should the notification say something along the lines of "This work is now on its Xnd attempt"?

**Comment by SigmasonicX** [comment]
This is different from "attempts", which refers to a work getting rejected and having to be resubmitted. A glitch allowing a user to submit the same story twice at the same time shouldn't count toward that.

**Comment by Figments** [comment]
> This is different from "attempts", which refers to a work getting rejected and having to be resubmitted. A glitch allowing a user to submit the same story twice at the same time shouldn't count toward that.

this wouldn't be possible at all, though, especially not with a `UNIQUE` constraint on `work_id`s

**Review by SigmasonicX — APPROVED** [review]
LGTM

**Pull request merged**
